const CURRCONV_API_URL = process.env.REACT_APP_API_URL_CURRCONV
const FRANKFURTER_API_URL = process.env.REACT_APP_API_URL_FRANKFURTER

export const CONVERT_ENDPOINT_PATH = `${CURRCONV_API_URL}/convert`
export const COMPARE_ENDPOINT_PATH = `${FRANKFURTER_API_URL}`
